# Generated by Django 5.2.11 on 2026-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('partido', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=2)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('presenca', models.FloatField(help_text='Percentual de presença (0 a 100)')),
                ('em_exercicio', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Deputados',
                'ordering': ['nome'],
            },
        ),
    ]
