# Generated by Django 5.2.11 on 2026-03-18 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrenteParlamentar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uri', models.URLField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=300)),
                ('id_legislatura', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uri', models.URLField(blank=True, null=True)),
                ('sigla', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=300)),
                ('tipo_orgao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=15, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('uri', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uri', models.URLField(blank=True, null=True)),
                ('sigla_tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('ementa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='deputado',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='deputado',
            name='em_exercicio',
        ),
        migrations.RemoveField(
            model_name='deputado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='deputado',
            name='presenca',
        ),
        migrations.RemoveField(
            model_name='deputado',
            name='sexo',
        ),
        migrations.AddField(
            model_name='deputado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='id_legislatura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='sigla_partido',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='sigla_uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='url_foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deputados.partido'),
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('uri', models.URLField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('aprovada', models.IntegerField(blank=True, null=True)),
                ('orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deputados.orgao')),
                ('proposicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deputados.proposicao')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_voto', models.CharField(max_length=30)),
                ('data_registro', models.DateTimeField(blank=True, null=True)),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='deputados.deputado')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='deputados.votacao')),
            ],
            options={
                'unique_together': {('votacao', 'deputado')},
            },
        ),
    ]
