# Generated by Django 5.2.11 on 2026-03-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputados', '0002_frenteparlamentar_orgao_partido_proposicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputado',
            name='sexo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
