# Generated by Django 5.2.11 on 2026-03-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputados', '0003_deputado_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputado',
            name='condicao_eleitoral',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='data_falecimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='municipio_nascimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='nome_civil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='situacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deputado',
            name='uf_nascimento',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
