# Generated by Django 5.2.11 on 2026-04-01 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputados', '0004_deputado_condicao_eleitoral_deputado_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposicaoAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposicoes_autoradas', to='deputados.deputado')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='deputados.proposicao')),
            ],
            options={
                'verbose_name_plural': 'Autores de Proposições',
                'unique_together': {('proposicao', 'deputado')},
            },
        ),
    ]
