# Generated by Django 5.2.11 on 2026-03-18 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deputados', '0002_frenteparlamentar_orgao_partido_proposicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeputadoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislatura', models.IntegerField()),
                ('presenca_percentual', models.FloatField(help_text='Percentual de presença nas votações (0 a 100)')),
                ('votacoes_presente', models.IntegerField(help_text='Qtd de votações em que o deputado votou')),
                ('votacoes_total', models.IntegerField(help_text='Total de votações na legislatura')),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='deputados.deputado')),
            ],
            options={
                'verbose_name': 'Presença de Deputado',
                'verbose_name_plural': 'Presenças de Deputados',
                'ordering': ['-presenca_percentual'],
                'unique_together': {('deputado', 'legislatura')},
            },
        ),
    ]
