# Generated by Django 5.2.11 on 2026-02-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deputados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilaridadeVotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similaridade', models.FloatField(help_text='Percentual de similaridade de votos (0 a 100)')),
                ('deputado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similaridades_como_1', to='deputados.deputado')),
                ('deputado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similaridades_como_2', to='deputados.deputado')),
            ],
            options={
                'verbose_name_plural': 'Similaridades de Votos',
                'ordering': ['-similaridade'],
                'unique_together': {('deputado_1', 'deputado_2')},
            },
        ),
    ]
