# Generated by Django 5.2.11 on 2026-03-18 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputados', '0002_frenteparlamentar_orgao_partido_proposicao_and_more'),
        ('grafos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrafoAresta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislatura', models.IntegerField()),
                ('similaridade', models.FloatField(help_text='Percentual de similaridade de votos (0 a 100)')),
                ('votos_em_comum', models.IntegerField(default=0, help_text='Qtd de votações em que ambos participaram')),
                ('deputado_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arestas_como_1', to='deputados.deputado')),
                ('deputado_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arestas_como_2', to='deputados.deputado')),
            ],
            options={
                'verbose_name_plural': 'Arestas do Grafo',
                'ordering': ['-similaridade'],
            },
        ),
        migrations.DeleteModel(
            name='SimilaridadeVotos',
        ),
        migrations.AddIndex(
            model_name='grafoaresta',
            index=models.Index(fields=['legislatura', 'similaridade'], name='grafos_graf_legisla_0cf901_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grafoaresta',
            unique_together={('deputado_1', 'deputado_2', 'legislatura')},
        ),
    ]
