# Generated by Django 5.2.11 on 2026-04-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafos', '0002_grafoaresta_delete_similaridadevotos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafoaresta',
            name='coautoria',
            field=models.IntegerField(default=0, help_text='Qtd de projetos de lei coautorados pelo par'),
        ),
    ]
